export const ROUTES = {
  AUTH: {
    SIGN_IN: '/sign-in',
    SIGN_UP: '/sign-up',
    FORGOT_PASSWORD: '/forgot-password',
    OTP: '/otp',
  },
  MAIN: {
    DASHBOARD: '/',
    PRODUCTS: '/products',
    PRODUCT_NEW: '/products/new',
    PRODUCT_DETAIL: '/products/$productId',
    PRODUCT_EDIT: '/products/$productId/edit',
    ORDERS: '/orders',
    ORDER_DETAIL: '/orders/$orderId',
    CATEGORIES: '/categories',
    INVENTORY: '/inventory',
    INVENTORY_MOVEMENTS: '/inventory/movements',
    RETURNS: '/returns',
    CUSTOMERS: '/customers',
    CUSTOMER_DETAIL: '/customers/$customerId',
    PROMOTIONS: '/promotions',
    SHIPPING: '/shipping',
    REPORTS: '/reports',
    STAFF: '/staff',
    ROLES: '/roles',
    SETTINGS: '/settings',
    AUDIT_LOGS: '/audit-logs',
  },
} as const;
